"""add Index

Revision ID: 671df584217d
Revises: 835635f2c735
Create Date: 2025-09-17 01:15:17.647257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671df584217d'
down_revision: Union[str, Sequence[str], None] = '835635f2c735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_lab_id', 'audit_logs', ['lab_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_brainstorm_sessions_created_by', 'brainstorm_sessions', ['created_by'], unique=False)
    op.create_index('ix_brainstorm_sessions_lab_id', 'brainstorm_sessions', ['lab_id'], unique=False)
    op.create_index('ix_conversations_lab_id', 'conversations', ['lab_id'], unique=False)
    op.create_index('ix_conversations_owner_id', 'conversations', ['owner_id'], unique=False)
    op.create_index('ix_job_steps_job_id', 'job_steps', ['job_id'], unique=False)
    op.create_index('ix_kg_schemas_created_by', 'kg_schemas', ['created_by'], unique=False)
    op.create_index('ix_kg_schemas_lab_id', 'kg_schemas', ['lab_id'], unique=False)
    op.create_index('ix_lab_members_lab_id', 'lab_members', ['lab_id'], unique=False)
    op.create_index('ix_lab_members_user_id', 'lab_members', ['user_id'], unique=False)
    op.create_index('ix_labs_active_connection_id', 'labs', ['active_connection_id'], unique=False)
    op.create_index('ix_labs_active_schema_id', 'labs', ['active_schema_id'], unique=False)
    op.create_index('ix_labs_owner_id', 'labs', ['owner_id'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_parent_message_id', 'messages', ['parent_message_id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_neo4j_connections_lab_id', 'neo4j_connections', ['lab_id'], unique=False)
    op.create_index('ix_neo4j_connections_schema_id', 'neo4j_connections', ['schema_id'], unique=False)
    op.create_index('ix_paper_analysis_paper_id', 'paper_analysis', ['paper_id'], unique=False)
    op.create_index('ix_processing_jobs_lab_id', 'processing_jobs', ['lab_id'], unique=False)
    op.create_index('ix_research_keywords_session_id', 'research_keywords', ['session_id'], unique=False)
    op.create_index('ix_research_papers_lab_id', 'research_papers', ['lab_id'], unique=False)
    op.create_index('ix_user_oauth_accounts_user_id', 'user_oauth_accounts', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_verifications_user_id', 'user_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_verifications_user_id', table_name='user_verifications')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_oauth_accounts_user_id', table_name='user_oauth_accounts')
    op.drop_index('ix_research_papers_lab_id', table_name='research_papers')
    op.drop_index('ix_research_keywords_session_id', table_name='research_keywords')
    op.drop_index('ix_processing_jobs_lab_id', table_name='processing_jobs')
    op.drop_index('ix_paper_analysis_paper_id', table_name='paper_analysis')
    op.drop_index('ix_neo4j_connections_schema_id', table_name='neo4j_connections')
    op.drop_index('ix_neo4j_connections_lab_id', table_name='neo4j_connections')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_parent_message_id', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_index('ix_labs_owner_id', table_name='labs')
    op.drop_index('ix_labs_active_schema_id', table_name='labs')
    op.drop_index('ix_labs_active_connection_id', table_name='labs')
    op.drop_index('ix_lab_members_user_id', table_name='lab_members')
    op.drop_index('ix_lab_members_lab_id', table_name='lab_members')
    op.drop_index('ix_kg_schemas_lab_id', table_name='kg_schemas')
    op.drop_index('ix_kg_schemas_created_by', table_name='kg_schemas')
    op.drop_index('ix_job_steps_job_id', table_name='job_steps')
    op.drop_index('ix_conversations_owner_id', table_name='conversations')
    op.drop_index('ix_conversations_lab_id', table_name='conversations')
    op.drop_index('ix_brainstorm_sessions_lab_id', table_name='brainstorm_sessions')
    op.drop_index('ix_brainstorm_sessions_created_by', table_name='brainstorm_sessions')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_lab_id', table_name='audit_logs')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    # ### end Alembic commands ###
